language: generic
dist: trusty

aliases:
  -  &linux_deps
    - build-essential
    - automake
    - autoconf
    - bison
    - mcpp
    - flex
    - lsb-release
    - libncurses5-dev
    - libtool
  - &linuxgcc
    stage: Testing
    sudo: false
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *linux_deps
        - g++-7
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
  - &linuxclang
    stage: Testing
    os: linux
    # enable sudo for libomp-dev in debian-sid repository
    # It clashes with the existing repo if we add it here.
    # sudo: required
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        - ubuntu-toolchain-r-test
        packages:
        - *linux_deps
        - clang-4.0
        - libstdc++-7-dev
    #install: ".travis/linux/clang_install.sh"
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
  - &linuxpackage
    stage: Packaging
    os: linux
    sudo: false
    services: docker
  - &osxgcc
    stage: Testing
    os: osx
    osx_image: xcode8.3
    install: ".travis/osx/install_withgcc.sh"
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
    cache:
      directories: $HOME/Library/Caches/Homebrew
  - &osxclang
    <<: *osxgcc
    install: ".travis/osx/install.sh"
    compiler: clang
    language: cpp
  - &osxpackage
    <<: *osxclang
    stage: Packaging
    before_script: ".travis/init_make_package.sh"
    script: ".travis/osx/make_package.sh"
  - &gcc_environment CC=gcc-7 CXX=g++-7
  - &clang_environment CC=clang-4.0 CXX=clang++-4.0

jobs:
  include:
# Style check stage
  - stage: Style
    os: linux
    sudo: false
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-format-4.0
    script: ".travis/run_test_format.sh"

# Testing stage (-j8,-c -j8)
  - <<: *linuxgcc
    env:
    - "gcc-setup"
    - *gcc_environment
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *linuxclang
    env:
    - "clang-setup"
    - *clang_environment
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *osxclang
    env:
    - "clang-setup"
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *osxgcc
    env:
    - "gcc-setup"
    - *gcc_environment
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS="-j8,-c -j8"

# Testing stage with 64bit RamDomains (-j8,-c -j8, no 32bit Semantic tests)
  - <<: *linuxgcc
    before_script: ".travis/init_test_64bit.sh"
    env:
    - "gcc-64bit-setup"
    - *gcc_environment
    - SOUFFLE_CATEGORY=Unit,Syntactic,Interface,Profile,Provenance SOUFFLE_CONFS="-j8,-c -j8"

# Testing stage with engine option (-c -j8 -efile, FastEvaluation and select others)
  - <<: *linuxgcc
    env:
    - "gcc-efile"
    - *gcc_environment
    - SOUFFLE_CATEGORY=FastEvaluation,Interface,Profile,Provenance SOUFFLE_CONFS="-c -j8 -efile"

# Testing stage (-j8,-c -j8)
  - <<: *linuxgcc
    env:
    - "gcc-evaluation"
    - *gcc_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *linuxclang
    env:
    - "clang-evaluation"
    - *clang_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *osxclang
    env:
    - "clang-evaluation"
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"

# Packaging stage
  # Test make install installs a working souffle.
  - <<: *linuxpackage
    script: docker run -v `pwd`:/souffle ubuntu:xenial /bin/sh -c "cd /souffle && .travis/linux/install_debian_deps.sh && .travis/init_make_package.sh && .travis/test_make_install.sh"
    env: "debian-make-install"
  # Make the linux deb packages.
  - <<: *linuxpackage
    script: docker run -v `pwd`:/souffle ubuntu:xenial /bin/sh -c "cd /souffle && .travis/linux/install_debian_deps.sh && .travis/init_make_package.sh && .travis/linux/make_package.sh"
    env: "debian-package"
    before_deploy:
      - .travis/bintray_json.sh
    # deploy to bintray if we're in the souffle-lang repo
    # https://docs.travis-ci.com/user/deployment/bintray
    deploy:
      - provider: bintray
        skip-cleanup: true
        file: bintray-deb-unstable.json
        user: souffle-lang
        key: $BINTRAY_KEY
        on:
          branch: master
          repo: souffle-lang/souffle
      - provider: bintray
        skip-cleanup: true
        file: bintray-deb-stable.json
        user: souffle-lang
        key: $BINTRAY_KEY
        on:
          branch: master
          repo: souffle-lang/souffle
          tags: true
      - provider: releases
        skip_cleanup: true
        api_key:
          secure: rWSbE68NuY6ULn7moKvbH1WmOGWljm2R5DwIO6HXmBa8yP3SVk5zSIL/cFoWB5cvqEqIvvRqypRcZuR75lMYefhUq93S/uk8/Sh420g0u3Hcav6wvOmEaQIs/1lkIkIV5GitLKIIXzTgfJ28jnTrrHrVuD6b4bcNJhXcMOxhMG8yeCxgi9DCc3sugBdFPMIOCDU9nb4SCjTq0YluWcTfFzpkD+QtgZzeLyopjldOAAAWx7ZqbpzHxTHJHH/9UZEI8OVDAEhPOawygZaGonUDfVSk04YdPl+Y5pRMXcC2MRVjwaDZVmuHKzJ2QSPwDkr199aONbJLJEpDTBv/ABLIjl+W/js5+hO8jFMdZopFvhOBAhYMka+AQQg860TJhgiXs00Kp/UPGr9OXZnEHWRjdo8KuWz/akOhAvWfnxeoxaBY32V0H1RKIwVvdCE5rekMmJDqgqTJTivIU9w/tDID7I7uvJaZ2bxygMwec+Jfnwlw8iPndWLrU8kVpPkGLVmnllrNAoUvH0wURc9kqwW8pzVyU660yqPNslcFjLIJWWyPgSxI4FcEySu7HaEFy/ukNmLpI+XSpQu8SYofK+xiklkd5fNq7LDn28AvVd8AyZnuBSA3PqzR3Yma1isAsiObcNLtTh6yvx7Nu3GcfcYkmjqFjcpRfww27F+6P0w5Rbk=
        file_glob: true
        file: deploy/*
        on:
          branch: master
          repo: souffle-lang/souffle
          tags: true
  # Make the centos rpm packages.
  - <<: *linuxpackage
    script: docker run -v `pwd`:/souffle centos:7 /bin/sh -c "cd /souffle && .travis/linux/install_centos_deps.sh && .travis/linux/make_centos_package.sh"
    env: "centos-package"
    before_deploy:
      - .travis/bintray_json.sh rpm
    # deploy to bintray if we're in the souffle-lang repo
    # https://docs.travis-ci.com/user/deployment/bintray
    deploy:
      - provider: bintray
        skip-cleanup: true
        file: bintray-rpm-unstable.json
        user: souffle-lang
        key: $BINTRAY_KEY
        on:
          all_branches: true
      - provider: bintray
        skip-cleanup: true
        file: bintray-rpm-stable.json
        user: souffle-lang
        key: $BINTRAY_KEY
        on:
          branch: master
          repo: souffle-lang/souffle
          tags: true

  # Make the fedora rpm packages.
  - <<: *linuxpackage
    script: docker run -v `pwd`:/souffle fedora:27 /bin/sh -c "cd /souffle && .travis/linux/install_fedora_deps.sh && .travis/linux/make_fedora_package.sh"
    env: "fedora-package"
    before_deploy:
      - .travis/bintray_json.sh rpm
    # deploy to bintray if we're in the souffle-lang repo
    # https://docs.travis-ci.com/user/deployment/bintray
    deploy:
      - provider: bintray
        skip-cleanup: true
        file: bintray-rpm-unstable.json
        user: souffle-lang
        key: $BINTRAY_KEY
        on:
          all_branches: true
      - provider: bintray
        skip-cleanup: true
        file: bintray-rpm-stable.json
        user: souffle-lang
        key: $BINTRAY_KEY
        on:
          branch: master
          repo: souffle-lang/souffle
          tags: true
  # Make the OSX packages.
  - <<: *osxpackage
    env: "osx-package"
  # Generate doxygen html
  - stage: Packaging
    env: "documenting"
    os: linux
    sudo: false
    addons:
      apt:
        packages:
        - *linux_deps
        - doxygen
        - graphviz
    script: "./bootstrap && ./configure && make doxygen-doc"
    # update the gh-pages branch with doxygen output if the required github token has been set
    # https://pages.github.com/
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GHPAGES_TOKEN
      keep-history: false
      local-dir: doc/html
      on:
        branch: master
        condition: -v $GHPAGES_TOKEN

after_failure:
  - ".travis/after_failure.sh"
