language: generic
dist: trusty

aliases:
  -  &linux_deps
    - build-essential
    - automake
    - autoconf
    - bison
    - flex
    - lsb-release
    - libncurses5-dev
    - libtool
  - &linuxgcc
    stage: Testing
    sudo: false
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *linux_deps
        - g++-7
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
  - &linuxclang
    stage: Testing
    os: linux
    # enable sudo for libomp-dev in debian-sid repository
    # It clashes with the existing repo if we add it here.
    sudo: required
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - *linux_deps
        - clang-4.0
    install: ".travis/linux/clang_install.sh"
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
  - &linuxpackage
    stage: Packaging
    os: linux
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - *linux_deps
        - g++-7
        - devscripts
        - debhelper
        - fakeroot
        - openjdk-7-jdk
    before_script: ".travis/init_make_package.sh"
    script: ".travis/linux/make_package.sh"
  - &osxclang
    stage: Testing
    os: osx
    compiler: clang
    osx_image: xcode8.2
    install: ".travis/osx/install.sh"
    before_script: ".travis/init_test.sh"
    script: ".travis/run_test.sh"
    cache:
      directories: $HOME/Library/Caches/Homebrew
  - &osxpackage
    <<: *osxclang
    stage: Packaging
    before_script: ".travis/init_make_package.sh"
    script: ".travis/osx/make_package.sh"
  - &gcc_environment CC=gcc-7 CXX=g++-7
  - &clang_environment CC=clang-4.0 CXX=clang++-4.0

jobs:
  include:
#Style check stage
  - stage: Style
    os: linux
    sudo: false
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-format-4.0
    script: ".travis/run_test_format.sh"

# Testing stage
  - <<: *linuxgcc
    env:
    - *gcc_environment
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance
  - <<: *linuxclang
    env:
    - *clang_environment
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance
  - <<: *osxclang
    env:
    - SOUFFLE_CATEGORY=Unit,Syntactic,Semantic,Interface,Profile,Provenance SOUFFLE_CONFS=",-c,-c -p profile.log,-p profile.log"

  - <<: *linuxgcc
    env:
    - *gcc_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS=",-c"
  - <<: *linuxclang
    env:
    - *clang_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS=",-c"
  - <<: *osxclang
    env:
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS=",-c"

  - <<: *linuxgcc
    env:
    - *gcc_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"
  - <<: *linuxclang
    env:
    - *clang_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-j8,-c -j8"

  - <<: *linuxgcc
    env:
    - *gcc_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-p profile.log, -c -p profile.log"
  - <<: *linuxclang
    env:
    - *clang_environment
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-p profile.log, -c -p profile.log"
  - <<: *osxclang
    env:
    - SOUFFLE_CATEGORY=Evaluation SOUFFLE_CONFS="-p profile.log, -c -p profile.log"

# Packaging stage
  # Make the linux deb packages.
  - <<: *linuxpackage
    env:
    - *gcc_environment
  # Make the OSX packages.
  - <<: *osxpackage

after_failure:
  - ".travis/after_failure.sh"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rWSbE68NuY6ULn7moKvbH1WmOGWljm2R5DwIO6HXmBa8yP3SVk5zSIL/cFoWB5cvqEqIvvRqypRcZuR75lMYefhUq93S/uk8/Sh420g0u3Hcav6wvOmEaQIs/1lkIkIV5GitLKIIXzTgfJ28jnTrrHrVuD6b4bcNJhXcMOxhMG8yeCxgi9DCc3sugBdFPMIOCDU9nb4SCjTq0YluWcTfFzpkD+QtgZzeLyopjldOAAAWx7ZqbpzHxTHJHH/9UZEI8OVDAEhPOawygZaGonUDfVSk04YdPl+Y5pRMXcC2MRVjwaDZVmuHKzJ2QSPwDkr199aONbJLJEpDTBv/ABLIjl+W/js5+hO8jFMdZopFvhOBAhYMka+AQQg860TJhgiXs00Kp/UPGr9OXZnEHWRjdo8KuWz/akOhAvWfnxeoxaBY32V0H1RKIwVvdCE5rekMmJDqgqTJTivIU9w/tDID7I7uvJaZ2bxygMwec+Jfnwlw8iPndWLrU8kVpPkGLVmnllrNAoUvH0wURc9kqwW8pzVyU660yqPNslcFjLIJWWyPgSxI4FcEySu7HaEFy/ukNmLpI+XSpQu8SYofK+xiklkd5fNq7LDn28AvVd8AyZnuBSA3PqzR3Yma1isAsiObcNLtTh6yvx7Nu3GcfcYkmjqFjcpRfww27F+6P0w5Rbk=
  file_glob: true
  file: deploy/*
  on:
    tags: true
